export const teacherConstants = {
  TEACHER_LOGIN_REQUEST: "TEACHER_LOGIN_REQUEST",
  TEACHER_LOGIN_SUCCESS: "TEACHER_LOGIN_SUCCESS",
  TEACHER_LOGIN_FAILURE: "TEACHER_LOGIN_FAILURE",

  TEACHER_LOGOUT_REQUEST: "TEACHER_LOGOUT_REQUEST",
  TEACHER_LOGOUT_SUCCESS: "TEACHER_LOGOUT_SUCCESS",
  TEACHER_LOGOUT_FAILURE: "TEACHER_LOGOUT_FAILURE",

  TEACHER_REGISTER_REQUEST: "TEACHER_REGISTER_REQUEST",
  TEACHER_REGISTER_SUCCESS: "TEACHER_REGISTER_SUCCESS",
  TEACHER_REGISTER_FAILURE: "TEACHER_REGISTER_FAILURE",

  ADD_NEW_TEACHER_REQEUST: "ADD_NEW_TEACHER_REQEUST",
  ADD_NEW_TEACHER_SUCCESS: "ADD_NEW_TEACHER_SUCCESS",
  ADD_NEW_TEACHER_FAILURE: "ADD_NEW_TEACHER_FAILURE",
};

export const studentConstants = {
  STUDENT_LOGIN_REQUEST: "STUDENT_LOGIN_REQUEST",
  STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
  STUDENT_LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",

  STUDENT_LOGOUT_REQUEST: "STUDENT_LOGOUT_REQUEST",
  STUDENT_LOGOUT_SUCCESS: "STUDENT_LOGOUT_SUCCESS",
  STUDENT_LOGOUT_FAILURE: "STUDENT_LOGOUT_FAILURE",

  GET_ALL_STUDENTS_REQEUST: "GET_ALL_STUDENTS_REQEUST",
  GET_ALL_STUDENTS_SUCCESS: "GET_ALL_STUDENTS_SUCCESS",
  GET_ALL_STUDENTS_FAILURE: "GET_ALL_STUDENTS_FAILURE",

  ADD_NEW_STUDENT_REQEUST: "ADD_NEW_STUDENT_REQEUST",
  ADD_NEW_STUDENT_SUCCESS: "ADD_NEW_STUDENT_SUCCESS",
  ADD_NEW_STUDENT_FAILURE: "ADD_NEW_STUDENT_FAILURE",

  DELETE_STUDENT_REQEUST: "DELETE_STUDENT_REQEUST",
  DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAILURE: "DELETE_STUDENT_FAILURE",

  UPDATE_STUDENT_REQEUST: "UPDATE_STUDENT_REQEUST",
  UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
  UPDATE_STUDENT_FAILURE: "UPDATE_STUDENT_FAILURE",
};


export const adminConstants = {
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",

  ADMIN_LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
  ADMIN_LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
  ADMIN_LOGOUT_FAILURE: "ADMIN_LOGOUT_FAILURE",

  ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
  ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
  ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE",

  ADD_NEW_ADMIN_REQEUST: "ADD_NEW_ADMIN_REQEUST",
  ADD_NEW_ADMIN_SUCCESS: "ADD_NEW_ADMIN_SUCCESS",
  ADD_NEW_ADMIN_FAILURE: "ADD_NEW_ADMIN_FAILURE",
};

export const hodConstants = {
  HOD_LOGIN_REQUEST: "HOD_LOGIN_REQUEST",
  HOD_LOGIN_SUCCESS: "HOD_LOGIN_SUCCESS",
  HOD_LOGIN_FAILURE: "HOD_LOGIN_FAILURE",

  HOD_LOGOUT_REQUEST: "HOD_LOGOUT_REQUEST",
  HOD_LOGOUT_SUCCESS: "HOD_LOGOUT_SUCCESS",
  HOD_LOGOUT_FAILURE: "HOD_LOGOUT_FAILURE",

  HOD_REGISTER_REQUEST: "HOD_REGISTER_REQUEST",
  HOD_REGISTER_SUCCESS: "HOD_REGISTER_SUCCESS",
  HOD_REGISTER_FAILURE: "HOD_REGISTER_FAILURE",

  ADD_NEW_HOD_REQEUST: "ADD_NEW_HOD_REQEUST",
  ADD_NEW_HOD_SUCCESS: "ADD_NEW_HOD_SUCCESS",
  ADD_NEW_HOD_FAILURE: "ADD_NEW_HOD_FAILURE",
};


export const principalConstants = {
  PRINCIPAL_LOGIN_REQUEST: "PRINCIPAL_LOGIN_REQUEST",
  PRINCIPAL_LOGIN_SUCCESS: "PRINCIPAL_LOGIN_SUCCESS",
  PRINCIPAL_LOGIN_FAILURE: "PRINCIPAL_LOGIN_FAILURE",

  PRINCIPAL_LOGOUT_REQUEST: "PRINCIPAL_LOGOUT_REQUEST",
  PRINCIPAL_LOGOUT_SUCCESS: "PRINCIPAL_LOGOUT_SUCCESS",
  PRINCIPAL_LOGOUT_FAILURE: "PRINCIPAL_LOGOUT_FAILURE",

  PRINCIPAL_REGISTER_REQUEST: "PRINCIPAL_REGISTER_REQUEST",
  PRINCIPAL_REGISTER_SUCCESS: "PRINCIPAL_REGISTER_SUCCESS",
  PRINCIPAL_REGISTER_FAILURE: "PRINCIPAL_REGISTER_FAILURE",

  ADD_NEW_PRINCIPAL_REQEUST: "ADD_NEW_PRINCIPAL_REQEUST",
  ADD_NEW_PRINCIPAL_SUCCESS: "ADD_NEW_PRINCIPAL_SUCCESS",
  ADD_NEW_PRINCIPAL_FAILURE: "ADD_NEW_PRINCIPAL_FAILURE",
};

export const userRoleConstants = {
  ADMIN: "ADMIN",
  USER: "USER",
};
