export const teacherConstants = {
  TEACHER_LOGIN_REQUEST: "TEACHER_LOGIN_REQUEST",
  TEACHER_LOGIN_SUCCESS: "TEACHER_LOGIN_SUCCESS",
  TEACHER_LOGIN_FAILURE: "TEACHER_LOGIN_FAILURE",

  TEACHER_LOGOUT_REQUEST: "TEACHER_LOGOUT_REQUEST",
  TEACHER_LOGOUT_SUCCESS: "TEACHER_LOGOUT_SUCCESS",
  TEACHER_LOGOUT_FAILURE: "TEACHER_LOGOUT_FAILURE",
};
